---
version: "3"
services:
  kong:
    # image: kong:local
    build: .
    container_name: kong
    depends_on:
      - nginx
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8002:8002"
      - "8444:8444"
    environment:
      KONG_LOG_LEVEL: debug
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl http2
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl http2
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002, 0.0.0.0:10445 ssl
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_PLUGINS: bundled,xml-json-transformer
      KONG_NGINX_WORKER_PROCESSES: 2
      KONG_LICENSE_DATA: ""
    volumes:
      - ./kong/plugins/xml-json-transformer:/usr/local/share/lua/5.1/kong/plugins/xml-json-transformer
      - ./kong/kong.yml:/etc/kong/kong.yml
  nginx:
    image: cgr.dev/chainguard/nginx
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx-www:/usr/share/nginx/html
